export const cipherCentralBankAbi = [
  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "encryptedAmount", type: "bytes32" },
      { name: "inputProof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "requestWithdraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "encryptedAmount", type: "bytes32" },
      { name: "inputProof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "completeWithdraw",
    stateMutability: "nonpayable",
    inputs: [{ name: "requestIndex", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "completeWithdrawMany",
    stateMutability: "nonpayable",
    inputs: [{ name: "requestIndices", type: "uint256[]" }],
    outputs: [],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "getPendingWithdrawCount",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getPendingWithdraw",
    stateMutability: "view",
    inputs: [
      { name: "user", type: "address" },
      { name: "requestIndex", type: "uint256" },
    ],
    outputs: [
      { name: "csbaAmountEnc", type: "bytes32" },
      { name: "unlockBlock", type: "uint64" },
      { name: "active", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "sharePriceScaled",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "monthlyRateBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint64" }],
  },
  {
    type: "function",
    name: "BLOCKS_PER_MONTH",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint64" }],
  },
] as const;
